version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: inotes_db_container
    restart: always
    environment:
      POSTGRES_USER: jodemvel
      POSTGRES_PASSWORD: jodemvel
      POSTGRES_DB: inotes_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  data:
    driver: local